/*
 * The vendored VPU model must not drift from upstream.
 *
 * `src/vendor/vpu-model.js` is a copy of aquilon-vpu-map's `public/vpu.js`,
 * because a Chrome extension has to contain every file it loads. A copy that
 * quietly diverges is worse than no copy at all: two tools would draw different
 * conclusions from the same device and both would look right.
 *
 * So this compares the body against an upstream checkout when there is one
 * beside this repo, and skips when there is not — a clone on its own machine
 * should still have a green test run.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const vendored = join(here, '..', 'src', 'vendor', 'vpu-model.js');
const upstream = join(here, '..', '..', 'aquilon-vpu-map', 'public', 'vpu.js');

const MARKER = ' * ------------------------------------------------------------------------- */';

/** The vendored file minus the provenance header this repo adds. */
function body(text) {
  const end = text.indexOf(MARKER);
  return (end < 0 ? text : text.slice(end + MARKER.length)).trim();
}

test('the vendored VPU model matches upstream', async (t) => {
  let source;
  try {
    source = await readFile(upstream, 'utf8');
  } catch {
    t.skip('no aquilon-vpu-map checkout beside this repo');
    return;
  }
  const copy = await readFile(vendored, 'utf8');
  assert.equal(body(copy), source.trim(),
    'src/vendor/vpu-model.js has drifted — run: npm run sync:vpu-model');
});

test('the vendored file still carries its provenance', async () => {
  const copy = await readFile(vendored, 'utf8');
  assert.match(copy, /VENDORED — do not edit this file here/);
  assert.match(copy, /\* Commit:\s+[0-9a-f]{40}/, 'provenance must name a real upstream commit');
});
