/*
 * Nothing vendored may drift from upstream.
 *
 * Three things are copied into `src/vendor/` rather than re-derived here:
 *
 *   vpu-model.js      aquilon-vpu-map's VPU model
 *   mynah-lang.mjs    mynah's command language, as its own build output
 *   surface/          awj-surface's control-surface engine and profiles
 *
 * In every case the reason is the same, and it is not convenience: two
 * implementations of one grammar, one device model or one decode table will
 * eventually disagree, and both will look right. A copy makes that impossible
 * — but only while something checks the copy.
 *
 * Each test compares against an upstream checkout when there is one beside
 * this repo, and skips when there is not, so a clone on its own machine still
 * has a green run.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const vendored = join(here, '..', 'src', 'vendor', 'vpu-model.js');
const upstream = join(here, '..', '..', 'aquilon-vpu-map', 'public', 'vpu.js');
const mynahVendored = join(here, '..', 'src', 'vendor', 'mynah-lang.mjs');
const mynahUpstream = join(here, '..', '..', 'mynah', 'dist-lang', 'mynah-lang.mjs');
const surfaceDir = join(here, '..', 'src', 'vendor', 'surface');
const surfaceUpstream = join(here, '..', '..', 'awj-surface');

const MARKER = ' * ------------------------------------------------------------------------- */';

/** The vendored file minus the provenance header this repo adds. */
function body(text) {
  const end = text.indexOf(MARKER);
  return (end < 0 ? text : text.slice(end + MARKER.length)).trim();
}

test('the vendored VPU model matches upstream', async (t) => {
  let source;
  try {
    source = await readFile(upstream, 'utf8');
  } catch {
    t.skip('no aquilon-vpu-map checkout beside this repo');
    return;
  }
  const copy = await readFile(vendored, 'utf8');
  assert.equal(body(copy), source.trim(),
    'src/vendor/vpu-model.js has drifted — run: npm run sync:vpu-model');
});

test('the vendored file still carries its provenance', async () => {
  const copy = await readFile(vendored, 'utf8');
  assert.match(copy, /VENDORED — do not edit this file here/);
  assert.match(copy, /\* Commit:\s+[0-9a-f]{40}/, 'provenance must name a real upstream commit');
});

test('the vendored Mynah language matches upstream', async (t) => {
  let source;
  try {
    source = await readFile(mynahUpstream, 'utf8');
  } catch {
    t.skip('no mynah checkout beside this repo (or dist-lang not built)');
    return;
  }
  const copy = await readFile(mynahVendored, 'utf8');
  assert.equal(body(copy), source.trim(),
    'src/vendor/mynah-lang.mjs has drifted — run: npm run sync:mynah-lang');
});

test('the Mynah language is usable, and agrees with our own path builder', async () => {
  /* The point of vendoring the grammar rather than re-typing it. These two
     were derived independently — mynah from the Web RCS bundle, core/paths.js
     from live captures — so identical output is real corroboration, and a
     mismatch means one of them moved. */
  const lang = await import('../src/vendor/mynah-lang.mjs');
  const { CMD } = await import('../src/core/paths.js');

  const run = (text) => {
    const parsed = lang.parse(text);
    assert.notEqual(parsed.ok, false, `${text} should parse`);
    const compiled = lang.compile(parsed.command ?? parsed);
    assert.ok(compiled.ok, `${text} should compile`);
    return compiled;
  };

  assert.deepEqual(run('Take Screen 1').ops[0].path.toWs(), CMD.take('S1').path);
  assert.deepEqual(
    run('Recall Screen 1 Memory 5').ops[0].path.toWs(),
    CMD.recallScreenPreset(5, 'S1', 'PREVIEW').path);

  /* Abbreviation is the grammar's headline feature; if the table moved, this
     is where it shows. */
  const long = run('Recall Screen 1 Memory 5');
  const short = run('R Sc 1 Me 5');
  assert.deepEqual(short.ops[0].path.toWs(), long.ops[0].path.toWs());
});

test('the vendored surface engine matches upstream, file for file', async (t) => {
  const { createHash } = await import('node:crypto');
  const { readdir } = await import('node:fs/promises');
  let manifest;
  try {
    manifest = JSON.parse(await readFile(join(surfaceDir, 'MANIFEST.json'), 'utf8'));
  } catch {
    assert.fail('src/vendor/surface/MANIFEST.json is missing — run: npm run sync:surface-core');
  }

  /* The manifest is the copy's own record; check it first, so a hand-edited
     vendored file is caught even with no upstream to compare against. */
  for (const [rel, hash] of Object.entries(manifest.files)) {
    const body = await readFile(join(surfaceDir, rel));
    assert.equal(createHash('sha256').update(body).digest('hex'), hash,
      `src/vendor/surface/${rel} was edited in place — edits belong upstream`);
  }
  assert.match(manifest.commit, /^[0-9a-f]{40}$|^unknown$/);

  try {
    await readdir(join(surfaceUpstream, 'core'));
  } catch {
    t.skip('no awj-surface checkout beside this repo');
    return;
  }
  for (const [rel, hash] of Object.entries(manifest.files)) {
    const from = rel.startsWith('profiles/')
      ? join(surfaceUpstream, rel)
      : join(surfaceUpstream, 'core', rel);
    const body = await readFile(from);
    assert.equal(createHash('sha256').update(body).digest('hex'), hash,
      `${rel} has drifted — run: npm run sync:surface-core`);
  }
});

test('the surface engine decodes MIDI and writes store paths', async () => {
  /* The whole reason this core is vendored: it turns controller bytes into
     writes, and it must produce OUR path shape without translation. */
  const { Engine } = await import('../src/vendor/surface/engine.js');
  const { MidiSurface } = await import('../src/vendor/surface/surface.js');
  const profile = JSON.parse(
    await readFile(join(surfaceDir, 'profiles', 'apc40.json'), 'utf8'));

  const surface = new MidiSurface(profile, () => {});
  const decoded = surface.handle(new Uint8Array([0xB0, 7, 100]));
  assert.equal(decoded.control, 'cc:0:7');
  assert.equal(decoded.kind, 'absolute');
  assert.ok(decoded.value > 0.78 && decoded.value < 0.79, '100/127');

  /* A store stub: enough for the engine to resolve a selection against. */
  const store = { get: () => undefined };
  const engine = new Engine(store, profile, {});
  const writes = [];
  engine.addEventListener('write', (ev) => writes.push(...(ev.detail.writes || [])));

  engine.input(decoded);
  await new Promise((r) => setTimeout(r, 60));

  /* With nothing read back from the device there is no pickup to hold against,
     so the move lands. What matters is the SHAPE of the path. */
  if (writes.length) {
    assert.ok(Array.isArray(writes[0].path), 'writes carry a store path array');
    assert.equal(writes[0].path[0], 'device', 'rooted the way this repo roots paths');
    assert.ok(writes[0].path.includes('pp'), 'store spelling, not AWJ @props');
  }
});
