/*
 * Variables — the half both ends share. No DOM, no I/O.
 *
 * Two kinds of name, told apart by their first character, the way mynah's
 * grammar tells them apart (`src/vendor/mynah-lang.mjs`, `variables.ts`
 * upstream):
 *
 *   $S1.width          a SYSTEM variable — read off the store mirror, live,
 *                      generated by walking what the switcher has. Read-only.
 *   @gap               a USER variable — an operator's own: a number, or a sum
 *                      over numbers and other variables. Kept per switcher.
 *
 * Both reach a value through one resolver, `resolve(name, kind)`, the shape
 * mynah's `vars` and `core/expr.js` both take — so the Console, the vendor's
 * numeric fields and anything else that evaluates arithmetic agree to the
 * digit about what `$S1.width/2` is.
 *
 * ## The system catalogue is generated, not listed
 *
 * Every name is produced by walking the objects the store already describes —
 * the destinations in service, each one's allocated layers, the fitted inputs
 * and outputs, the loaded stills, the timers — through `core/dialect.js`, so a
 * rig with more screens has more variables and a Midra has Midra's. Nothing
 * here lists store leaves; the catalogue grows with the rig. The namespace is
 * in `docs/VARIABLES.md` and the descriptions below are what the panel shows.
 *
 * ## The rules that are load-bearing
 *
 * - ⚠️ **A role is resolved, never assumed.** `$S1.PGM.L2.x` names a layer in
 *   whichever buffer is program *now*. It goes through `presetBanks()` — the
 *   one sanctioned conversion — and while the screen is mid-take
 *   (`settled: false`) it is **an error, not a guess**: the buffer that is
 *   program is changing hands, and the wrong answer is a layer moved on air.
 *   The same rule the Layer panel and the gang keep.
 * - ⚠️ **Only allocated layers have variables.** A preset carries geometry for
 *   every slot, allocated or not (`core/screens.js` says why that matters); a
 *   variable for an unallocated slot would read a stale full-frame rectangle
 *   with complete confidence. `dialect.fittedLayers` says which exist.
 * - **A size is reported or it is an error.** `listDestinations` falls back to
 *   1920×1080 for a screen that has not said — right for drawing a card, wrong
 *   for arithmetic, which would put a plausible number into a field.
 * - **A label is text**, listed and shown but refused inside arithmetic.
 * - **A user variable that depends on itself is a cycle**, found before
 *   anything is evaluated and reported for every member with the loop spelled
 *   out — never a stack overflow, never a half-evaluated value.
 * - **Names are matched without regard to case** (`$s1.WIDTH` is `$S1.width`),
 *   in a `Map`: `$constructor` is unknown, not Object's own.
 */

import { dialectFor } from '../../src/core/dialect.js';
import { listDestinations, presetBanks } from '../../src/core/screens.js';
import { detectPlatform } from '../../src/core/platform.js';
import { evaluate, variablesIn } from '../../src/core/expr.js';

/** The stored document's version, so a later change can migrate rather than guess. */
export const VARIABLES_VERSION = 1;

/** What a user variable may be called: the same shape mynah's lexer reads after a sigil. */
export const NAME = /^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)*$/;
/** Long enough for `wall.left.width`, short enough for a table cell. */
export const NAME_MAX = 40;
/** Matches `core/expr.js`'s cap: a definition is evaluated by it. */
export const DEFINITION_MAX = 160;
/** More than anybody types by hand; a bound on the file and the cycle search. */
export const MAX_VARIABLES = 200;

/** The two roles a layer variable may name, and the buffer word each means. */
export const ROLES = [
  { key: 'PGM', mode: 'program', label: 'program' },
  { key: 'PVW', mode: 'preview', label: 'preview' }
];

const ok = (value) => ({ ok: true, value });
const no = (error) => ({ ok: false, error });

/* ============================================================== system */

/**
 * One catalogue entry. `read()` answers live, every time it is called, so an
 * entry can be held across store frames; only the set of names is a snapshot.
 *
 * @typedef {{
 *   name: string, group: string, type: 'number'|'text', unit: string|null,
 *   description: string, read: () => ({ok: true, value: number|string} | {ok: false, error: string})
 * }} Entry
 */

/** A number off the store, or the sentence saying why there is none. */
const number = (v, why) => (typeof v === 'number' && Number.isFinite(v) ? ok(v) : no(why));
const words = (v) => ok(typeof v === 'string' ? v : '');

/**
 * Every system variable this store can answer, in the order the panel lists
 * them: the device, the screens, the auxes, inputs, outputs, stills, timers.
 *
 * @param {{get: Function, ready?: boolean}} store
 * @returns {Entry[]}
 */
export function systemCatalogue(store) {
  const dialect = dialectFor(store);
  if (!dialect) return [];
  const out = [];
  const add = (group, name, type, unit, description, read) =>
    out.push({ name, group, type, unit, description, read });

  /* ---- the device ---- */
  const used = listDestinations(store);
  add('Device', 'device.name', 'text', null, 'What the switcher calls its range — AQUILON, Midra 4K', () => words(detectPlatform(store).name));
  add('Device', 'device.model', 'text', null, 'Model code — NLC_CMAX, PULSE', () => words(detectPlatform(store).model));
  add('Device', 'device.firmware', 'text', null, 'Firmware version', () => words(detectPlatform(store).firmware));
  add('Device', 'device.serial', 'text', null, 'Serial number', () => words(detectPlatform(store).serial));
  add('Device', 'device.screens', 'number', null, 'Screens in service', () =>
    ok(listDestinations(store).filter((d) => d.kind === 'screen').length));
  add('Device', 'device.auxes', 'number', null, 'Auxiliary screens in service', () =>
    ok(listDestinations(store).filter((d) => d.kind === 'aux').length));

  /* ---- screens and auxes, each with its layers per role ---- */
  for (const dest of used) addDestination(store, dialect, dest, add);

  /* ---- inputs ---- */
  for (const input of safe(() => dialect.inputFormats(store))) {
    const id = `IN${input.n}`;
    const g = `Input ${input.n}`;
    const live = () => safe(() => dialect.inputFormats(store)).find((i) => i.key === input.key) || null;
    const signal = (field, unit) => () => {
      const now = live();
      if (!now) return no(`${id} is no longer fitted`);
      if (!now.valid) return no(`${id} has no valid signal`);
      return number(now[field], `${id} has not reported its ${unit}`);
    };
    add(g, `${id}.width`, 'number', 'px', 'Width of the format it is receiving', signal('width', 'format'));
    add(g, `${id}.height`, 'number', 'px', 'Height of the format it is receiving', signal('height', 'format'));
    add(g, `${id}.rate`, 'number', 'Hz', 'Field rate of the format it is receiving', signal('rate', 'rate'));
    add(g, `${id}.valid`, 'number', null, '1 while a valid signal is present, 0 otherwise', () => {
      const now = live();
      return now ? ok(now.valid ? 1 : 0) : no(`${id} is no longer fitted`);
    });
    add(g, `${id}.format`, 'text', null, 'The format’s name as the switcher writes it', () => {
      const now = live();
      return now ? words(now.format) : no(`${id} is no longer fitted`);
    });
    if (input.label !== null) {
      add(g, `${id}.label`, 'text', null, 'Its label', () => words((live() || {}).label));
    }
  }

  /* ---- outputs ---- */
  for (const output of safe(() => dialect.outputFormats(store))) {
    const id = `OUT${output.n}`;
    const g = `Output ${output.n}`;
    const live = () => safe(() => dialect.outputFormats(store)).find((o) => o.key === output.key) || null;
    const field = (name, what) => () => {
      const now = live();
      return now ? number(now[name], `${id} has not reported its ${what}`) : no(`${id} is no longer fitted`);
    };
    add(g, `${id}.width`, 'number', 'px', 'Width of the raster it drives', field('width', 'raster'));
    add(g, `${id}.height`, 'number', 'px', 'Height of the raster it drives', field('height', 'raster'));
    add(g, `${id}.rate`, 'number', 'Hz', 'Its frame rate', field('rate', 'rate'));
    add(g, `${id}.x`, 'number', 'px', 'Left edge of its footprint on the screen’s canvas', field('x', 'place on the canvas'));
    add(g, `${id}.y`, 'number', 'px', 'Top edge of its footprint on the screen’s canvas', field('y', 'place on the canvas'));
    add(g, `${id}.cw`, 'number', 'px', 'Width of its footprint on the canvas — the raster with pitch applied', field('cw', 'footprint'));
    add(g, `${id}.ch`, 'number', 'px', 'Height of its footprint on the canvas', field('ch', 'footprint'));
    add(g, `${id}.screen`, 'text', null, 'The screen it shows, as the switcher names it', () => words((live() || {}).screen));
    add(g, `${id}.label`, 'text', null, 'Its label', () => words((live() || {}).label));
  }

  /* ---- stills ---- */
  for (const still of safe(() => dialect.stills(store))) {
    const id = `STILL${still.n}`;
    const g = `Still ${still.n}`;
    const live = () => safe(() => dialect.stills(store)).find((s) => s.key === still.key) || null;
    const field = (name) => () => {
      const now = live();
      return now ? number(now[name], `${id} has not reported its size`) : no(`${id} is no longer loaded`);
    };
    add(g, `${id}.width`, 'number', 'px', 'Width of the picture', field('width'));
    add(g, `${id}.height`, 'number', 'px', 'Height of the picture', field('height'));
    add(g, `${id}.label`, 'text', null, 'Its label', () => words((live() || {}).label));
  }

  /* ---- timers ---- */
  for (const timer of safe(() => dialect.timers(store))) {
    const id = `TIMER${timer.n}`;
    const g = `Timer ${timer.n}`;
    const live = () => safe(() => dialect.timers(store)).find((t) => t.key === timer.key) || {};
    add(g, `${id}.state`, 'text', null, 'IDLE, RUNNING, …, as the switcher writes it', () => words(live().state));
    add(g, `${id}.type`, 'text', null, 'What kind of timer — CURRENTTIME, COUNTDOWN, …', () => words(live().type));
    add(g, `${id}.label`, 'text', null, 'Its label', () => words(live().label));
    /* Only where the platform publishes one (LivePremier); see `dialect.timers`. */
    if (timer.value !== null) {
      add(g, `${id}.value`, 'number', null, 'The switcher’s own number, unconverted — milliseconds since midnight for a clock, read off one simulator', () =>
        number(live().value, `${id} has not reported a value`));
    }
  }

  return out;
}

/** A screen or an aux, its canvas, its take time and, per role, its layers. */
function addDestination(store, dialect, dest, add) {
  const { id } = dest;
  const g = dest.kind === 'screen' ? `Screen ${id.slice(1)}` : `Aux ${id.slice(1)}`;
  const live = () => listDestinations(store, { includeUnused: true }).find((d) => d.id === id) || null;
  const gone = () => no(`${id} is no longer in service`);

  add(g, `${id}.label`, 'text', null, 'Its label', () => { const d = live(); return d ? words(d.label) : gone(); });
  if (dest.canvas && dest.canvas.reported) {
    add(g, `${id}.width`, 'number', 'px', 'Canvas width, as applied', () => canvasSide(live(), 'width', id));
    add(g, `${id}.height`, 'number', 'px', 'Canvas height, as applied', () => canvasSide(live(), 'height', id));
  }
  add(g, `${id}.layers`, 'number', null, 'Layers the switcher has given it', () => {
    const d = live();
    return d ? number(d.layerCount, `${id} has not reported a layer count`) : gone();
  });
  add(g, `${id}.outputs`, 'number', null, 'Outputs it drives', () => {
    const d = live();
    return d ? number(d.outputCount, `${id} has not reported an output count`) : gone();
  });
  add(g, `${id}.takeTime`, 'number', 's', 'Its take time, in seconds', () => {
    const path = dialect.fadeTimePath(id);
    const tenths = path ? store.get(path) : undefined;
    return typeof tenths === 'number' ? ok(tenths / 10) : no(`${id} has not reported a take time`);
  });

  const layers = safe(() => dialect.fittedLayers(store, id));
  for (const role of ROLES) {
    const prefix = `${id}.${role.key}`;
    add(g, `${prefix}.memory`, 'number', null, `The memory ${role.label} was recalled from`, () => {
      const buffer = roleBuffer(store, id, role);
      if (!buffer.ok) return buffer;
      /* Slots count from 1; LivePremier reports 0 for a buffer that was not
         loaded from one, where a Midra reports null. */
      const held = (safe(() => dialect.assignments(store, id)) || {})[buffer.value];
      return held && Number.isFinite(held.slot) && held.slot > 0
        ? ok(held.slot)
        : no(`${id}’s ${role.label} was not recalled from a memory`);
    });
    for (const layer of layers) {
      const slot = layer.isNative ? 'NATIVE' : `L${layer.key}`;
      const what = layer.isNative ? 'NATIVE' : `Layer ${layer.key}`;
      const geometry = (field, unit) => () => {
        const buffer = roleBuffer(store, id, role);
        if (!buffer.ok) return buffer;
        const d = live();
        if (!d) return gone();
        if (!safe(() => dialect.fittedLayers(store, id)).some((f) => f.key === layer.key)) {
          return no(`${id} no longer has ${what.toLowerCase()} allocated`);
        }
        const geo = dialect.layerGeometry(store, d, buffer.value, layer.key);
        if (!geo) return no(`${id} ${slot} has no geometry in buffer ${buffer.value}`);
        if (field === 'source') return words(geo.source);
        return number(geo[field], `${id} ${slot} has not reported its ${unit}`);
      };
      const where = `${what} in ${role.label}`;
      add(g, `${prefix}.${slot}.x`, 'number', 'px', `${where}: X — the anchor point, as the X field shows it`, geometry('posH', 'position'));
      add(g, `${prefix}.${slot}.y`, 'number', 'px', `${where}: Y — the anchor point`, geometry('posV', 'position'));
      add(g, `${prefix}.${slot}.w`, 'number', 'px', `${where}: width`, geometry('sizeH', 'size'));
      add(g, `${prefix}.${slot}.h`, 'number', 'px', `${where}: height`, geometry('sizeV', 'size'));
      add(g, `${prefix}.${slot}.opacity`, 'number', null, `${where}: opacity, in the switcher’s 0–256`, geometry('opacity', 'opacity'));
      add(g, `${prefix}.${slot}.source`, 'text', null, `${where}: its source — LIVE_3, INPUT_2, NONE`, geometry('source', 'source'));
    }
  }
}

function canvasSide(dest, side, id) {
  if (!dest) return no(`${id} is no longer in service`);
  if (!dest.canvas || !dest.canvas.reported) return no(`${id} has not reported a canvas size`);
  return number(dest.canvas[side], `${id} has not reported a canvas size`);
}

/**
 * The buffer a role names on a destination, right now — or why not.
 *
 * `presetBanks()` is the one sanctioned conversion; this only refuses where
 * it says the answer is not to be trusted. ⚠️ Mid-take is a refusal, not the
 * letter that was program a moment ago.
 */
export function roleBuffer(store, id, role) {
  const banks = presetBanks(store, id);
  if (!banks.reported) return no(`${id} has not said which buffer is on air yet`);
  if (!banks.settled) {
    return no(`${id} is mid-take — ${role.label} is changing hands; it reads again when the transition lands`);
  }
  return ok(role.mode === 'program' ? banks.program : banks.preview);
}

/* Readers that can meet a store a platform shaped differently must not take
   the catalogue down with them; an empty list is the honest answer. */
function safe(fn) {
  try { const v = fn(); return Array.isArray(v) ? v : (v ?? []); } catch { return []; }
}

/**
 * A lookup over one catalogue, by name, without regard to case.
 *
 * `resolve` answers like mynah's `vars`: the entry's live value, a sentence
 * for a name that is understood and cannot be answered (`explain`), or
 * undefined for a name nobody has heard of.
 */
export function systemIndex(store) {
  const entries = systemCatalogue(store);
  const byName = new Map(entries.map((e) => [e.name.toLowerCase(), e]));
  return {
    entries,
    get: (name) => byName.get(String(name).toLowerCase()) || null,
    resolve(name) {
      const entry = byName.get(String(name).toLowerCase());
      if (entry) {
        try { return entry.read(); } catch (err) { return no(err && err.message ? err.message : 'could not be read'); }
      }
      return explain(store, name);
    }
  };
}

/**
 * Why a name that is not in the catalogue is not there, when that can be
 * said: a destination that is not in service, a layer that is not
 * allocated, a canvas that has not been reported. Otherwise undefined —
 * an unknown variable, which mynah and `core/expr.js` say in their words.
 */
export function explain(store, name) {
  const parts = String(name).split('.');
  const m = /^([SA])(\d+)$/i.exec(parts[0] || '');
  if (!m) return undefined;
  const id = m[1].toUpperCase() + m[2];
  const dest = listDestinations(store, { includeUnused: true }).find((d) => d.id === id);
  if (!dest) return undefined;
  if (!dest.isUsed) return no(`${id} is not in service on this switcher`);
  const field = (parts[1] || '').toLowerCase();
  if (parts.length === 2 && (field === 'width' || field === 'height')) {
    return no(`${id} has not reported a canvas size`);
  }
  const role = ROLES.find((r) => r.key.toLowerCase() === field);
  const slot = /^L(\d+)$/i.exec(parts[2] || '');
  if (role && slot && parts.length === 4) {
    return no(`${id} has no layer ${slot[1]} allocated — only allocated layers have variables`);
  }
  if (role && /^native$/i.test(parts[2] || '') && parts.length === 4) {
    return no(`${id} has no NATIVE layer allocated`);
  }
  return undefined;
}

/* ================================================================ user */

/** A random-enough id for a row, so a rename does not lose the caret. */
export const newId = () => 'v' + Math.random().toString(36).slice(2, 10);

const ID = /^[a-z0-9-]{1,40}$/;

/**
 * Coerce whatever was on disk into a document that cannot misbehave.
 *
 * In the spirit of `core/layer-names.js`: a hand-edited file must not cost an
 * operator their variables on a show day, so nothing is refused outright. A
 * row with no usable name is dropped, a second row with the same name (in any
 * case) is dropped, and a definition is kept as text whatever it says — an
 * unparseable one is reported where it is shown, which is more useful than
 * losing it.
 */
export function normalise(raw) {
  const rows = raw && typeof raw === 'object' && Array.isArray(raw.variables) ? raw.variables : [];
  const seen = new Set();
  const out = [];
  for (const row of rows) {
    if (!row || typeof row !== 'object') continue;
    const name = typeof row.name === 'string' ? row.name.trim() : '';
    if (!NAME.test(name) || name.length > NAME_MAX) continue;
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const value = typeof row.value === 'number' && Number.isFinite(row.value)
      ? String(row.value)
      : typeof row.value === 'string' ? row.value.replace(/\s+/g, ' ').trim() : '';
    out.push({ id: typeof row.id === 'string' && ID.test(row.id) ? row.id : newId(), name, value });
    if (out.length >= MAX_VARIABLES) break;
  }
  return { version: VARIABLES_VERSION, variables: out };
}

/**
 * Is this a name a user variable may have, beside these others?
 *
 * @returns {string|null} a sentence for the panel, or null when it is fine
 */
export function checkName(name, variables, selfId = null) {
  const n = String(name ?? '').trim();
  if (!n) return 'a variable needs a name';
  if (n.length > NAME_MAX) return `at most ${NAME_MAX} characters`;
  if (!NAME.test(n)) return 'letters, digits and _, starting with a letter — dots separate parts, as in wall.left';
  const clash = variables.find((v) => v.id !== selfId && v.name.toLowerCase() === n.toLowerCase());
  if (clash) return `@${clash.name} already exists`;
  return null;
}

/** The user variables a definition names, lower-cased, without evaluating it. */
export function referencesIn(definition) {
  return variablesIn(definition).filter((v) => v.sigil === '@').map((v) => v.name.toLowerCase());
}

/**
 * Every user variable that is part of a cycle, with the loop spelled out.
 *
 * Found before anything is evaluated, so evaluation can refuse a cycle by
 * name instead of discovering it by recursing into it. Tarjan's strongly
 * connected components: any component of two or more, or one that names
 * itself, is a cycle, and every member gets the same sentence.
 *
 * @param {Array<{name: string, value: string}>} variables
 * @returns {Map<string, string>} lower-cased name → `@a → @b → @a`
 */
export function findCycles(variables) {
  const byKey = new Map(variables.map((v) => [v.name.toLowerCase(), v]));
  const edges = new Map(variables.map((v) => [
    v.name.toLowerCase(),
    referencesIn(v.value).filter((k) => byKey.has(k))
  ]));

  let counter = 0;
  const index = new Map();
  const low = new Map();
  const onStack = new Set();
  const stack = [];
  const components = [];

  const strongConnect = (v) => {
    index.set(v, counter);
    low.set(v, counter);
    counter++;
    stack.push(v);
    onStack.add(v);
    for (const w of edges.get(v) || []) {
      if (!index.has(w)) {
        strongConnect(w);
        low.set(v, Math.min(low.get(v), low.get(w)));
      } else if (onStack.has(w)) {
        low.set(v, Math.min(low.get(v), index.get(w)));
      }
    }
    if (low.get(v) === index.get(v)) {
      const component = [];
      let w;
      do {
        w = stack.pop();
        onStack.delete(w);
        component.push(w);
      } while (w !== v);
      components.push(component);
    }
  };
  for (const v of edges.keys()) if (!index.has(v)) strongConnect(v);

  const cycles = new Map();
  for (const component of components) {
    const selfLoop = component.length === 1 && (edges.get(component[0]) || []).includes(component[0]);
    if (component.length < 2 && !selfLoop) continue;
    const members = new Set(component);
    /* Spelled from whichever member the operator listed first, so the
       sentence reads in their order rather than the search's. */
    const start = [...byKey.keys()].find((k) => members.has(k));
    const path = loopThrough(start, members, edges);
    const spelled = path.map((k) => '@' + byKey.get(k).name).join(' → ');
    for (const k of component) cycles.set(k, spelled);
  }
  return cycles;
}

/** One loop from `start` back to itself, inside a component, for the sentence. */
function loopThrough(start, members, edges) {
  const path = [start];
  const seen = new Set([start]);
  let at = start;
  for (;;) {
    const next = (edges.get(at) || []).filter((k) => members.has(k));
    if (next.includes(start)) return [...path, start];
    const step = next.find((k) => !seen.has(k));
    if (step === undefined) return [...path, start];
    path.push(step);
    seen.add(step);
    at = step;
  }
}

/**
 * Evaluate user variables over a system resolver.
 *
 * One evaluator per moment: values are memoised for its lifetime, so a
 * definition used ten times is evaluated once, and a fresh one is made for
 * the next keystroke or frame. Cycles are refused by name (see
 * `findCycles`), so the recursion below always ends.
 *
 * @param {Array<{name: string, value: string}>} variables
 * @param {(name: string) => object|undefined} system  `$` lookups
 */
export function createUserEvaluator(variables, system) {
  const byKey = new Map(variables.map((v) => [v.name.toLowerCase(), v]));
  const cycles = findCycles(variables);
  const memo = new Map();

  const resolver = (name, kind) => (kind === 'system' ? system(name) : user(name));

  function user(name) {
    const key = String(name).toLowerCase();
    const def = byKey.get(key);
    if (!def) return undefined;
    if (memo.has(key)) return memo.get(key);
    let answer;
    if (cycles.has(key)) {
      answer = no(`is part of a cycle: ${cycles.get(key)}`);
    } else if (!def.value.trim()) {
      answer = no('has no value yet');
    } else {
      const r = evaluate(def.value, { resolve: resolver });
      answer = r.ok ? ok(r.value) : no(r.error);
    }
    memo.set(key, answer);
    return answer;
  }

  return { resolver, user, cycles };
}

/**
 * The whole resolver a page or a server hands to mynah and to `core/expr.js`.
 *
 * @param {Array<{name: string, value: string}>} variables  the user's
 * @param {(name: string) => object|undefined} system      `$` lookups
 */
export function makeResolver(variables, system) {
  return createUserEvaluator(variables, system).resolver;
}

/**
 * The resolver for a process that holds no store — the OSC listener.
 *
 * ⚠️ System variables are refused with the reason, exactly as `server/osc.js`
 * refuses `preview` and `program`: the take state and the canvas are device
 * state, and this process has no mirror of it. A user variable is answered
 * when everything it depends on is user variables and numbers; one that
 * reaches a `$` is refused naming the `$` it reached.
 */
export function storelessResolver(variables) {
  return makeResolver(variables, () =>
    no('needs the switcher’s state, which this process does not hold — system variables work in the page (the Console, numeric fields), not over UDP'));
}
